name: Backend Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run tests with code coverage
        run: |
             export FLASK_APP=core/server.py
             flask db upgrade -d core/migrations/
             pytest -vvv -s tests/
      
      - name: Generate HTML coverage report
        run: |
          pytest --cov --cov-report=html:coverage_re
          echo "HTML report generated"
      
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: coverage_re/